blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://docs.rbln.ai/software/optimum/optimum_rbln.html
    about: Check our documentation before creating an issue
  - name: ğŸ› ï¸ Developers Community
    url: https://discuss.rebellions.ai/
    about: Join our developers community
  - name: ğŸ“§ Email Support
    url: mailto:support@rebellions.ai
    about: Contact our support team